# Lightweight local Pillager Campaigns development server.
allow-flight=false
allow-nether=false
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
force-gamemode=true
gamemode=survival
generate-structures=false
hardcore=false
level-name=world
level-type=minecraft\:flat
max-players=4
max-tick-time=60000
motd=Pillager Campaigns Harness
online-mode=false
op-permission-level=4
player-idle-timeout=0
pvp=true
server-ip=127.0.0.1
server-port=25566
simulation-distance=6
spawn-animals=false
spawn-monsters=true
spawn-npcs=false
spawn-protection=0
sync-chunk-writes=true
view-distance=6
white-list=false
